### PR TITLE
#BOT-1400 - Add method get contributor

### PR DESCRIPTION
**Pull request by Fahmus**
# Description

This PR fixes bug on create new customer: X-contributor not found

## Issue 

Issue link: BOT-1400

## Pull Request type 

This is a bug fix

### CODE REVIEW

**Comment by Fahmus** [comment]
jenkins, retest this please

**Comment by Netmisa** [comment]
Jenkins could you test this please.

**Comment by Fahmus** [comment]
Jenkins could you test this please

**Comment by Netmisa** [comment]
Jenkins could you test this please.

**Comment by Fahmus** [comment]
jenkins, retest this please

**Comment by Fahmus** [comment]
jenkins, retest this please

**Comment by Fahmus** [comment]
jenkins, retest this please

**Comment by Fahmus** [comment]
jenkins, retest this please

**Pull request merged**
