### PR TITLE
Symfony3 compatible

### PR DESCRIPTION
**Pull request by datanel**
fix 
```
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
| #  | Usage                                                                                                       | Line | Comment                                                                       |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
|    | /home/dquintanel/sources/canaltp/nmm-ihm.local.canaltp.fr/vendor/canaltp/nmm-portal-bundle/Form/Type/PerimeterType.php                                                                             |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
| 1  | Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface                       | 114  | since version 2.6, to be removed in 3.0. Use {@link OptionsResolver} instead. |
| 2  | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\PerimeterType->getName()                     | 109  | Deprecated since Symfony 2.8, to be removed in Symfony 3.0.                   |
|    |                                                                                                             |      |  Use the fully-qualified class name of the type instead.                      |
| 3  | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\PerimeterType->setDefaultOptions()           | 114  | since version 2.7, to be renamed in 3.0.                                      |
|    |                                                                                                             |      |  Use the method configureOptions instead. This method will be                 |
|    |                                                                                                             |      |  added to the FormTypeInterface with Symfony 3.0.                             |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
|    | /home/dquintanel/sources/canaltp/nmm-ihm.local.canaltp.fr/vendor/canaltp/nmm-portal-bundle/Form/Type/CustomerApplicationType.php                                                                   |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
| 4  | Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface                       | 48   | since version 2.6, to be removed in 3.0. Use {@link OptionsResolver} instead. |
| 5  | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\CustomerApplicationType->getName()           | 43   | Deprecated since Symfony 2.8, to be removed in Symfony 3.0.                   |
|    |                                                                                                             |      |  Use the fully-qualified class name of the type instead.                      |
| 6  | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\CustomerApplicationType->setDefaultOptions() | 48   | since version 2.7, to be renamed in 3.0.                                      |
|    |                                                                                                             |      |  Use the method configureOptions instead. This method will be                 |
|    |                                                                                                             |      |  added to the FormTypeInterface with Symfony 3.0.                             |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
|    | /home/dquintanel/sources/canaltp/nmm-ihm.local.canaltp.fr/vendor/canaltp/nmm-portal-bundle/Form/Type/CustomerType.php                                                                              |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
| 7  | Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface                       | 112  | since version 2.6, to be removed in 3.0. Use {@link OptionsResolver} instead. |
| 8  | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\CustomerType->getName()                      | 107  | Deprecated since Symfony 2.8, to be removed in Symfony 3.0.                   |
|    |                                                                                                             |      |  Use the fully-qualified class name of the type instead.                      |
| 9  | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\CustomerType->setDefaultOptions()            | 112  | since version 2.7, to be renamed in 3.0.                                      |
|    |                                                                                                             |      |  Use the method configureOptions instead. This method will be                 |
|    |                                                                                                             |      |  added to the FormTypeInterface with Symfony 3.0.                             |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
|    | /home/dquintanel/sources/canaltp/nmm-ihm.local.canaltp.fr/vendor/canaltp/nmm-portal-bundle/Form/Type/NavitiaEntityType.php                                                                         |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
| 10 | Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface                       | 103  | since version 2.6, to be removed in 3.0. Use {@link OptionsResolver} instead. |
| 11 | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\NavitiaEntityType->getName()                 | 98   | Deprecated since Symfony 2.8, to be removed in Symfony 3.0.                   |
|    |                                                                                                             |      |  Use the fully-qualified class name of the type instead.                      |
| 12 | Overriding deprecated method CanalTP\NmmPortalBundle\Form\Type\NavitiaEntityType->setDefaultOptions()       | 103  | since version 2.7, to be renamed in 3.0.                                      |
|    |                                                                                                             |      |  Use the method configureOptions instead. This method will be                 |
|    |                                                                                                             |      |  added to the FormTypeInterface with Symfony 3.0.                             |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
|    | /home/dquintanel/sources/canaltp/nmm-ihm.local.canaltp.fr/vendor/canaltp/nmm-portal-bundle/Twig/TokenExtension.php                                                                                 |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
| 13 | Overriding deprecated method CanalTP\NmmPortalBundle\Twig\TokenExtension->getName()                         | 39   | since 1.26 (to be removed in 2.0), not used anymore internally                |
| 14 | Overriding deprecated method CanalTP\NmmPortalBundle\Twig\TokenExtension->getName()                         | 39   | since 1.26 (to be removed in 2.0), not used anymore internally                |
+----+-------------------------------------------------------------------------------------------------------------+------+-------------------------------------------------------------------------------+
```

Relates to https://jira.kisio.org/browse/GN-60

:exclamation: dependency to https://github.com/CanalTP/SamCoreBundle/pull/51

### CODE REVIEW

**Comment by datanel** [comment]
Jenkins can you test this please?

**Comment by datanel** [comment]
Jenkins can you test this please?

**Comment by datanel** [comment]
Jenkins can you test this please?

**Comment by dvdn** [comment]
Yo bro' Retest this please !

**Comment by dvdn** [comment]
Rebased on current master :heavy_check_mark:

**Comment by dvdn** [comment]
:grey_exclamation:  Related tests are brokens because of dependency http://jenkins.ci.canaltp.fr/job/NMM%20Portal%20(Github)/929/

**Pull request merged**
